### ISSUE TITLE
Resource '/[Project Name]/test' does not exist when import bnd workspace

### ISSUE THREAD

**Issue by hieplq** [hengsin/idempiere#1]
I followed the steps to set up Eclipse:

1. Cloned the source code and switched to the bndtools branch.
2. Launched Eclipse and selected the [idempiere-root] directory as the workspace.
3. Imported the existing BND workspace.

However, I'm encountering an error message stating that the "/[Project Name]/test" directory does not exist in almost all projects.

![image](https://github.com/user-attachments/assets/b4e35110-62fb-43a5-9497-98ab8841ff55)

**Comment by hengsin** [comment]
https://github.com/hengsin/idempiere/commit/5b2846c5dcecbea8d14a6207d079893709cf883d
